version: '3.8'

services:
  backend:
    image: marwanmw/cloudmart-backend:__BUILD_NUMBER__
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 256M

  frontend:
    image: marwanmw/cloudmart-frontend:__BUILD_NUMBER__
    ports:
      - "80:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 256M