apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-db-pvc
  namespace: cloudmart
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-db
  namespace: cloudmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-db
  template:
    metadata:
      labels:
        app: identity-db
    spec:
      containers:
        - name: identity-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: identity-db-secret
          volumeMounts:
            - name: identity-db-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "identity_user", "-d", "identity_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "identity_user", "-d", "identity_db"]
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: identity-db-storage
          persistentVolumeClaim:
            claimName: identity-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: identity-db
  namespace: cloudmart
spec:
  selector:
    app: identity-db
  ports:
    - port: 5432
      targetPort: 5432
