apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cloudmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: marwanmw/cloudmart-frontend:latest
          ports:
            - containerPort: 3007
          env:
            - name: PORT
              value: "3007"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NEXT_PUBLIC_API_URL
              value: "/v1"
            - name: NEXT_PUBLIC_WS_URL
              value: ""
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cloudmart
spec:
  selector:
    app: frontend
  ports:
    - port: 3007
      targetPort: 3007
