all:
  children:
    jenkins:
      hosts:
        jenkins-1:
          ansible_host: 10.0.1.10
    kubernetes_master:
      hosts:
        k8s-master-1:
          ansible_host: 10.0.2.10
    kubernetes_workers:
      hosts:
        k8s-worker-1:
          ansible_host: 10.0.2.11
        k8s-worker-2:
          ansible_host: 10.0.2.12
    nginx:
      hosts:
        nginx-1:
          ansible_host: 10.0.3.10
    database:
      hosts:
        db-1:
          ansible_host: 10.0.4.10