apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: cloudmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: marwanmw/cloudmart-identity-service  
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@identity-db:5432/$(POSTGRES_DB)"
            - name: JWT_EXPIRES_IN
              value: "15m"
          envFrom:
            - secretRef:
                name: identity-db-secret
            - secretRef:
                name: jwt-secret
          readinessProbe:
            httpGet:
              path: api/v1/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: api/v1/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: cloudmart
spec:
  selector:
    app: identity-service
  ports:
    - port: 3000
      targetPort: 3000
