apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: cloudmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: wali23/cloudmart-payment-service
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@rabbitmq:5672"
          envFrom:
            - secretRef:
                name: payment-secret
            - secretRef:
                name: rabbitmq-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: cloudmart
spec:
  selector:
    app: payment-service
  ports:
    - port: 3000
      targetPort: 3000
