apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-service
  namespace: cloudmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-service
  template:
    metadata:
      labels:
        app: product-catalog-service
    spec:
      containers:
        - name: product-catalog-service
          image: marwanmw/cloudmart-product-catalog-service
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: catalog-db-secret
                  key: MONGODB_URI
          readinessProbe:
            httpGet:
              path: api/v1/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: api/v1/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  namespace: cloudmart
spec:
  selector:
    app: product-catalog-service
  ports:
    - port: 3000
      targetPort: 3000
